version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: was-contracts-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    external:
      name: n8n_default  # Використовуємо мережу n8n